# SQLite Configuration
spring.datasource.url=jdbc:sqlite:drone.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Disable Druid for SQLite
spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
